# Опасный фрагмент конфигурации sudoers для аудита
# Задание: обнаружить уязвимости повышения привилегий (Privilege Escalation via GTFOBins)

# 1. Младший системный администратор (должен только искать логи)
junior_admin ALL=(root) NOPASSWD: /usr/bin/find

# 2. Разработчик (должен редактировать только конфигурационный файл проекта)
dev_alice ALL=(root) /usr/bin/vim /etc/nginx/sites-available/project.conf

# 3. Резервное копирование
backup_user ALL=(root) NOPASSWD: /usr/bin/tar -czf *
