# /etc/sysctl.d/sysctl_hardened.conf
# Эталонные параметры сетевого стека и безопасности ядра Linux (CIS Benchmark)

# Отключение транзитной маршрутизации IPv4 (хост не является роутером)
net.ipv4.ip_forward = 0

# Запрет пакетов с Source Routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Игнорирование сообщений ICMP Redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0

# Включение строгой фильтрации обратного пути (защита от IP-спуфинга)
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Защита от SYN Flood атак (TCP SYN Cookies)
net.ipv4.tcp_syncookies = 1

# Запрет сохранения дампов памяти (coredump) для SUID-процессов
fs.suid_dumpable = 0

# Включение рандомизации адресного пространства (ASLR)
kernel.randomize_va_space = 2
